# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net


name: CD Pipe

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: build win64
      run: dotnet publish PolyVase.csproj --sc -c Release -r win-x64 -o release/win64
    - name: build win32
      run: dotnet publish PolyVase.csproj --sc -c Release -r win-x86 -o release/win32
    - name: buil linux64
      run: dotnet publish PolyVase.csproj --sc -c Release -r linux-x64 -o release/linux64

    - name: install zip
      run: sudo apt-get install zip

    - name: pack win64
      run: zip PolyVase-win64.zip release/win64/PolyVase.exe README.md LICENSE.md
    - name: pack win32
      run: zip PolyVase-win32.zip release/win32/PolyVase.exe README.md LICENSE.md      
    - name: pack linux64
      run: zip PolyVase-linux64.zip release/linux64/PolyVase README.md LICENSE.md
      
    - name: Get Tag
      env:
        ref: ${{ github.ref_name }}
      run:  echo "tag=v-$ref-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Create release
      run: gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${tag}" --generate-notes

    - name: Upload assets
      run: gh release upload "$tag" ./PolyVase-win64.zip#PolyVase-win64.zip ./PolyVase-win32.zip#PolyVase-win32.zip ./PolyVase-linux64.zip#PolyVase-linux64.zip --repo="$GITHUB_REPOSITORY"
